allowBuilds:
  '@tailwindcss/oxide': true
  '@tsparticles/engine': set this to true or false
  '@vercel/speed-insights': true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
